# Generated by Django 6.0.8 on 2026-08-07 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("long_url", models.URLField()),
                ("short_code", models.CharField(max_length=10, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "urls",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="urls_user_id_29c570_idx"),
                    models.Index(fields=["is_active"], name="urls_is_acti_ad181e_idx"),
                    models.Index(fields=["created_at"], name="urls_created_71be6f_idx"),
                    models.Index(fields=["expires_at"], name="urls_expires_52ec95_idx"),
                ],
            },
        ),
    ]
