# Generated by Django 6.0.8 on 2026-08-08 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClickEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referrer", models.URLField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=100, null=True)),
                ("device", models.CharField(blank=True, max_length=100, null=True)),
                ("clicked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_events",
                        to="shortener.url",
                    ),
                ),
            ],
            options={
                "db_table": "click_events",
                "ordering": ["-clicked_at"],
                "indexes": [
                    models.Index(
                        fields=["url", "-clicked_at"],
                        name="click_event_url_id_650ed4_idx",
                    ),
                    models.Index(
                        fields=["url", "ip_address"],
                        name="click_event_url_id_bd00ff_idx",
                    ),
                    models.Index(
                        fields=["country"], name="click_event_country_0c28d6_idx"
                    ),
                    models.Index(
                        fields=["browser"], name="click_event_browser_c07932_idx"
                    ),
                ],
            },
        ),
    ]
